---
- name: Check if rcon is already installed at the desired version.
  ansible.builtin.command: rcon --version
  register: common_rcon_check
  failed_when: false
  changed_when: false

- name: Install rcon-cli.
  when: common_rcon_check.rc != 0 or common_rcon_version not in (common_rcon_check.stdout | default(''))
  block:
    - name: Create temp extraction dir for rcon-cli.
      ansible.builtin.file:
        path: "/tmp/rcon-cli-{{ common_rcon_version }}"
        state: directory
        mode: "0755"

    - name: Download and extract rcon-cli.
      ansible.builtin.unarchive:
        src: "{{ common_rcon_url }}"
        dest: "/tmp/rcon-cli-{{ common_rcon_version }}"
        remote_src: true

    - name: Install rcon binary to /usr/local/bin.
      ansible.builtin.copy:
        src: "/tmp/rcon-cli-{{ common_rcon_version }}/rcon-cli"
        dest: /usr/local/bin/rcon-cli
        remote_src: true
        owner: root
        group: root
        mode: "0755"

    - name: Cleanup rcon temp files.
      ansible.builtin.file:
        path: "/tmp/rcon-cli-{{ common_rcon_version }}"
        state: absent
