---
# Variable configuration.
- name: Include variable configuration.
  ansible.builtin.include_tasks: variables.yml

# Setup/install tasks (OS-specific).
- name: Setup packages (Debian family).
  ansible.builtin.include_tasks: setup-Debian.yml
  when: ansible_facts.os_family == 'Debian'

- name: Configure FastDL site.
  ansible.builtin.import_tasks: configure.yml
